require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/RedundantBegin:
  Enabled: false

Layout/LineLength:
  Max: 150

Style/DoubleNegation:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false
